from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

import torch

from gradcam_repro.real_ct import RealCtDataset, load_real_ct_model
from gradcam_repro.train import resolve_device
from gradcam_repro.visualize import (
    DEFAULT_METHODS,
    DETAIL_RENDERERS,
    render_class_discriminability,
    render_method_grid,
    render_notgradcam_decomposition,
)


ROOT = Path(__file__).resolve().parents[1]
DATA_CACHE = ROOT / "artifacts" / "real_ct" / "msd_lung_presence_32.pt"
CHECKPOINT = ROOT / "artifacts" / "real_ct" / "real_ct_presence_cnn_32.pt"
OUTPUT_DIR = ROOT / "artifacts" / "figures"


class DatasetSubset:
    def __init__(self, dataset: RealCtDataset, indices: list[int]) -> None:
        self.dataset = dataset
        self.indices = indices

    def __len__(self) -> int:
        return len(self.indices)

    def __getitem__(self, idx: int):
        return self.dataset[self.indices[idx]]


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def rel(path: Path) -> str:
    return str(path.resolve().relative_to(ROOT))


def main() -> None:
    device = resolve_device("cpu")
    model = load_real_ct_model(CHECKPOINT, device)
    positive_dataset = RealCtDataset(DATA_CACHE, split="test", positive_only=True)
    mask_fractions = [
        (idx, float(positive_dataset[idx]["mask"].float().mean().item()))
        for idx in range(len(positive_dataset))
    ]
    candidate_indices = [
        idx
        for idx, fraction in sorted(mask_fractions, key=lambda row: row[1])
        if 0.05 <= fraction <= 0.2
    ]
    selected_indices = (candidate_indices or [idx for idx, _fraction in mask_fractions])[:3]
    dataset = DatasetSubset(positive_dataset, selected_indices)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    method_grid = OUTPUT_DIR / "method_grid.png"
    class_discriminability = OUTPUT_DIR / "class_discriminability.png"
    notgradcam_decomposition = OUTPUT_DIR / "notgradcam_decomposition.png"
    detail_figures = {
        method_name: OUTPUT_DIR / f"{method_name}_decomposition.png"
        for method_name in DETAIL_RENDERERS
    }

    render_method_grid(
        model=model,
        dataset=dataset,  # type: ignore[arg-type]
        output=method_grid,
        device=device,
        sample_count=3,
        methods=DEFAULT_METHODS,
    )
    render_class_discriminability(
        model=model,
        dataset=dataset,  # type: ignore[arg-type]
        output=class_discriminability,
        device=device,
        sample_idx=0,
        methods=["notgradcam", "gradcam", "layercam", "integrated_gradcam"],
    )
    render_notgradcam_decomposition(
        model=model,
        dataset=dataset,  # type: ignore[arg-type]
        output=notgradcam_decomposition,
        device=device,
        sample_idx=0,
    )
    for method_name, output_path in detail_figures.items():
        DETAIL_RENDERERS[method_name](
            model=model,
            dataset=dataset,  # type: ignore[arg-type]
            output=output_path,
            device=device,
            sample_idx=0,
        )

    figures = {
        "method_grid": method_grid,
        "class_discriminability": class_discriminability,
        "notgradcam_decomposition": notgradcam_decomposition,
        **{f"{name}_decomposition": path for name, path in detail_figures.items()},
    }
    manifest = {
        "schema": "gradcam-repro.figure-manifest.v1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generated_by": "uv run python scripts/render_real_ct_deck_figures.py",
        "experiment": "msd_lung_tumour_presence_patch_real_ct_gradcam",
        "dataset": {
            "name": "MSD Task06_Lung",
            "task": "tumour-present CT patch classification",
            "cache": rel(DATA_CACHE),
            "split": "test positive patches",
        },
        "checkpoint": {
            "path": str(CHECKPOINT.resolve()),
            "sha256": sha256_file(CHECKPOINT),
        },
        "parameters": {
            "samples": 3,
            "device": "cpu",
            "methods": DEFAULT_METHODS,
            "detail_sample_idx": 0,
            "selected_positive_indices": selected_indices,
        },
        "policy": "Deck image assets must be generated by experiment code and listed in this manifest.",
        "figures": [
            {
                "name": name,
                "path": rel(path),
                "sha256": sha256_file(path),
                "source": "scripts/render_real_ct_deck_figures.py",
            }
            for name, path in figures.items()
        ],
    }
    manifest_path = OUTPUT_DIR / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2))
    print(json.dumps({"figures": {k: str(v) for k, v in figures.items()}, "manifest": str(manifest_path)}, indent=2))


if __name__ == "__main__":
    torch.set_grad_enabled(True)
    main()
