"""Render a faithful RealCtCNN architecture diagram for the deck (slide 4).

The figure is generated by introspecting the actual `RealCtCNN` module and
running a 32^3 dummy input, so block shapes (channels x spatial) and the
per-stage op labels always match the real model. Reproducible:

    uv run python scripts/render_architecture_figure.py

Output: artifacts/figures/realct_architecture.png
"""
from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import torch
from matplotlib.patches import FancyArrowPatch, Polygon, Rectangle
from torch import nn

from gradcam_repro.model import RealCtCNN

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "artifacts" / "figures" / "realct_architecture.png"

# Deck palette
NAVY = "#13181E"
ORANGE = "#E8602C"
GREY_FRONT = "#D7DEE6"
GREY_TOP = "#E9EEF3"
GREY_SIDE = "#B9C4CF"
TAP_FRONT = "#F7C9A6"
TAP_TOP = "#FBE2CD"
TAP_SIDE = "#EBA66F"
MUTED = "#5B6670"


def stage_op_label(stage: nn.Module) -> str:
    """Build an accurate op string by introspecting a Sequential stage."""
    convs = [m for m in stage.modules() if isinstance(m, nn.Conv3d)]
    pools = [m for m in stage.modules() if isinstance(m, nn.MaxPool3d)]
    k = convs[0].kernel_size[0] if convs else 3
    n = len(convs)
    conv_txt = f"{n}×Conv {k}³" if n > 1 else f"Conv {k}³"
    if pools:
        return f"{conv_txt}\n+ Pool ↓2"
    return f"{conv_txt}\nno pool"


def volume_width(spatial, max_spatial=32):
    """Front-face width of a volume block; single source of truth for layout."""
    return 0.45 + 0.70 * (spatial / max_spatial)


def draw_volume(ax, cx, cy, spatial, channels, *, tap=False, max_spatial=32):
    """Draw a pseudo-3D volume box; face size ~ spatial, depth ~ channels."""
    w = volume_width(spatial, max_spatial)
    h = 0.80 + 1.45 * (spatial / max_spatial)
    depth = 0.15 + 0.45 * (channels / 32.0)
    dx, dy = depth * 0.9, depth * 0.6
    front_c, top_c, side_c = (
        (TAP_FRONT, TAP_TOP, TAP_SIDE) if tap else (GREY_FRONT, GREY_TOP, GREY_SIDE)
    )
    x0, y0 = cx - w / 2, cy - h / 2
    # right side
    ax.add_patch(Polygon([(x0 + w, y0), (x0 + w + dx, y0 + dy),
                          (x0 + w + dx, y0 + h + dy), (x0 + w, y0 + h)],
                         closed=True, facecolor=side_c, edgecolor=NAVY, lw=1.1))
    # top
    ax.add_patch(Polygon([(x0, y0 + h), (x0 + dx, y0 + h + dy),
                          (x0 + w + dx, y0 + h + dy), (x0 + w, y0 + h)],
                         closed=True, facecolor=top_c, edgecolor=NAVY, lw=1.1))
    # front
    ax.add_patch(Rectangle((x0, y0), w, h, facecolor=front_c, edgecolor=NAVY, lw=1.3))
    return w, h, dx, dy


def arrow(ax, x1, x2, y, label):
    ax.add_patch(FancyArrowPatch((x1, y), (x2, y), arrowstyle="-|>",
                                 mutation_scale=14, lw=1.6, color=NAVY))
    ax.text((x1 + x2) / 2, y + 0.16, label, ha="center", va="bottom",
            fontsize=8.0, color=MUTED, linespacing=1.25)


def main() -> None:
    model = RealCtCNN().eval()
    x = torch.zeros(1, 1, 32, 32, 32)
    with torch.no_grad():
        _, feats = model(x, return_features=True)

    # Block specs straight from the real model.
    blocks = [
        {"name": "input", "spatial": x.shape[-1], "channels": x.shape[1],
         "sub": "CT patch", "tap": False},
        {"name": "stage1", "spatial": feats["stage1"].shape[-1],
         "channels": feats["stage1"].shape[1], "sub": "", "tap": False},
        {"name": "stage2", "spatial": feats["stage2"].shape[-1],
         "channels": feats["stage2"].shape[1], "sub": "", "tap": True},
        {"name": "stage3", "spatial": feats["stage3"].shape[-1],
         "channels": feats["stage3"].shape[1], "sub": "", "tap": False},
    ]
    ops = [stage_op_label(model.stage1), stage_op_label(model.stage2),
           stage_op_label(model.stage3)]

    fig, ax = plt.subplots(figsize=(11.8, 3.8), dpi=200)
    ax.set_xlim(0, 13.8)
    ax.set_ylim(-0.3, 4.2)
    ax.axis("off")

    centers = [1.4, 4.35, 7.2, 9.85]
    baseline = 2.05
    rights = []
    for c, blk in zip(centers, blocks):
        w, h, dx, dy = draw_volume(ax, c, baseline, blk["spatial"], blk["channels"],
                                   tap=blk["tap"])
        rights.append(c + w / 2 + dx)
        # label: channels x spatial^3
        ax.text(c, baseline - h / 2 - 0.30, f"{blk['channels']} × {blk['spatial']}³",
                ha="center", va="top", fontsize=10.5, fontweight="bold", color=NAVY)
        ax.text(c, baseline - h / 2 - 0.62, blk["name"], ha="center", va="top",
                fontsize=9.0, color=MUTED)
        if blk["sub"]:
            ax.text(c, baseline - h / 2 - 0.90, blk["sub"], ha="center", va="top",
                    fontsize=8.0, color=MUTED, style="italic")
        if blk["tap"]:
            ax.text(c, baseline + h / 2 + dy + 0.18, "CAM tap", ha="center", va="bottom",
                    fontsize=9.0, fontweight="bold", color=ORANGE)

    # arrows + op labels between volume blocks
    for i in range(3):
        next_left = centers[i + 1] - volume_width(blocks[i + 1]["spatial"]) / 2
        arrow(ax, rights[i] + 0.08, next_left - 0.08, baseline, ops[i])

    # head: GAP -> FC -> 2 logits  (drawn as a compact node group)
    head_x = 12.5
    arrow(ax, rights[3] + 0.08, head_x - 0.5, baseline, "GAP + FC\n32→2")
    ax.add_patch(Rectangle((head_x - 0.42, baseline - 0.62), 0.84, 1.24,
                           facecolor="#FFFFFF", edgecolor=NAVY, lw=1.3))
    ax.add_patch(Rectangle((head_x - 0.27, baseline + 0.06), 0.54, 0.32,
                           facecolor=ORANGE, edgecolor="none"))
    ax.add_patch(Rectangle((head_x - 0.27, baseline - 0.40), 0.54, 0.32,
                           facecolor=GREY_SIDE, edgecolor="none"))
    ax.text(head_x, baseline - 0.62 - 0.30, "2 logits", ha="center", va="top",
            fontsize=10.5, fontweight="bold", color=NAVY)
    ax.text(head_x, baseline - 0.62 - 0.62, "head", ha="center", va="top",
            fontsize=9.0, color=MUTED)

    fig.subplots_adjust(left=0.005, right=0.995, top=0.99, bottom=0.01)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(OUT, dpi=200, transparent=False, facecolor="white")
    print(f"wrote {OUT}")
    # also echo the introspected facts for verification
    for blk in blocks:
        print(f"  {blk['name']:7} C={blk['channels']:>2} spatial={blk['spatial']}³ tap={blk['tap']}")
    for nm, op in zip(("stage1", "stage2", "stage3"), ops):
        print(f"  {nm} op: {op!r}")


if __name__ == "__main__":
    main()
