from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from .data import CrossHalfDataset
from .evaluate import save_scores, score_attributions
from .real_ct import (
    DEFAULT_CACHE as DEFAULT_REAL_CT_CACHE,
    DEFAULT_CHECKPOINT as DEFAULT_REAL_CT_CHECKPOINT,
    DEFAULT_FIGURE_DIR as DEFAULT_REAL_CT_FIGURE_DIR,
    DEFAULT_RAW_ROOT as DEFAULT_REAL_CT_RAW_ROOT,
    DEFAULT_SCORE_PATH as DEFAULT_REAL_CT_SCORE_PATH,
    REAL_CT_FAST_METHODS,
    RealCtDataset,
    RealCtPreprocessConfig,
    RealCtTrainConfig,
    load_cache_summary,
    load_real_ct_model,
    preprocess_msd_lung,
    render_real_ct_grid,
    render_real_ct_single_case,
    score_real_ct_attributions,
    train_real_ct_model,
)
from .train import TrainConfig, load_model, resolve_device, train_model
from .visualize import (
    DETAIL_RENDERERS,
    render_class_discriminability,
    render_method_grid,
    render_notgradcam_decomposition,
)


DEFAULT_CHECKPOINT = Path("artifacts/checkpoints/toy_cnn.pt")
DEFAULT_FIGURE_DIR = Path("artifacts/figures")
DEFAULT_SCORE_PATH = Path("artifacts/scores/attribution_scores.json")
DEFAULT_NODE = Path("/Users/baiduli/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/bin/node")


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def format_manifest_path(path: Path) -> str:
    resolved = path.resolve()
    try:
        return str(resolved.relative_to(Path.cwd().resolve()))
    except ValueError:
        return str(resolved)


def write_figure_manifest(
    output_dir: Path,
    checkpoint: Path,
    figures: dict[str, Path],
    samples: int,
    seed: int,
    device: str,
    detail_sample_idx: int,
) -> Path:
    output_manifest_path = output_dir / "manifest.json"
    checkpoint = checkpoint.resolve()
    payload = {
        "schema": "gradcam-repro.figure-manifest.v1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generated_by": "uv run gradcam-repro demo",
        "experiment": "toy_1voxel_3axis_cross_box_distractors_gradcam",
        "checkpoint": {
            "path": str(checkpoint),
            "sha256": sha256_file(checkpoint),
        },
        "parameters": {
            "samples": samples,
            "seed": seed,
            "device": device,
            "detail_sample_idx": detail_sample_idx,
        },
        "policy": "Deck image assets must be generated by experiment code and listed in this manifest.",
        "figures": [
            {
                "name": name,
                "path": format_manifest_path(path),
                "sha256": sha256_file(path),
                "source": "src/gradcam_repro/visualize.py",
            }
            for name, path in figures.items()
        ],
    }
    output_manifest_path.write_text(json.dumps(payload, indent=2))
    return output_manifest_path


def add_train_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--output", type=Path, default=DEFAULT_CHECKPOINT)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--eval-every-steps", type=int, default=10)
    parser.add_argument("--early-stop-acc", type=float, default=0.95)
    parser.add_argument("--train-size", type=int, default=1200)
    parser.add_argument("--val-size", type=int, default=200)
    parser.add_argument("--test-size", type=int, default=120)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--lr", type=float, default=3e-3)
    parser.add_argument("--weight-decay", type=float, default=1e-3)


def command_train(args: argparse.Namespace) -> None:
    config = TrainConfig(
        train_size=args.train_size,
        val_size=args.val_size,
        test_size=args.test_size,
        batch_size=args.batch_size,
        epochs=args.epochs,
        eval_every_steps=args.eval_every_steps,
        early_stop_acc=args.early_stop_acc,
        lr=args.lr,
        weight_decay=args.weight_decay,
        seed=args.seed,
    )
    result = train_model(args.output, config=config, device_name=args.device)
    print(json.dumps(result, indent=2))


def command_demo(args: argparse.Namespace) -> None:
    device = resolve_device(args.device)
    model = load_model(args.checkpoint, device)
    dataset = CrossHalfDataset(args.samples, seed=args.seed)
    detail_sample_idx = next(
        (idx for idx in range(len(dataset)) if int(dataset[idx]["label"]) == 1),
        0,
    )
    args.output_dir.mkdir(parents=True, exist_ok=True)
    method_grid = args.output_dir / "method_grid.png"
    class_discriminability = args.output_dir / "class_discriminability.png"
    notgradcam_decomposition = args.output_dir / "notgradcam_decomposition.png"
    detail_figures = {
        method_name: args.output_dir / f"{method_name}_decomposition.png"
        for method_name in DETAIL_RENDERERS
    }
    render_method_grid(
        model,
        dataset,
        output=method_grid,
        device=device,
        sample_count=args.samples,
    )
    render_class_discriminability(
        model,
        dataset,
        output=class_discriminability,
        device=device,
        sample_idx=0,
    )
    render_notgradcam_decomposition(
        model,
        dataset,
        output=notgradcam_decomposition,
        device=device,
        sample_idx=detail_sample_idx,
    )
    for method_name, output_path in detail_figures.items():
        DETAIL_RENDERERS[method_name](
            model,
            dataset,
            output=output_path,
            device=device,
            sample_idx=detail_sample_idx,
        )
    manifest = write_figure_manifest(
        output_dir=args.output_dir,
        checkpoint=args.checkpoint,
        figures={
            "method_grid": method_grid,
            "class_discriminability": class_discriminability,
            "notgradcam_decomposition": notgradcam_decomposition,
            **{f"{name}_decomposition": path for name, path in detail_figures.items()},
        },
        samples=args.samples,
        seed=args.seed,
        device=args.device,
        detail_sample_idx=detail_sample_idx,
    )
    print(
        json.dumps(
            {
                "method_grid": str(method_grid),
                "class_discriminability": str(class_discriminability),
                "notgradcam_decomposition": str(notgradcam_decomposition),
                "detail_figures": {name: str(path) for name, path in detail_figures.items()},
                "detail_sample_idx": detail_sample_idx,
                "manifest": str(manifest),
            },
            indent=2,
        )
    )


def command_score(args: argparse.Namespace) -> None:
    device = resolve_device(args.device)
    model = load_model(args.checkpoint, device)
    dataset = CrossHalfDataset(args.samples, seed=args.seed)
    scores = score_attributions(model, dataset, device)
    save_scores(scores, args.output)
    print(json.dumps({"scores": str(args.output), "summary": scores}, indent=2))


def command_deck(args: argparse.Namespace) -> None:
    repo_root = Path(__file__).resolve().parents[2]
    script = repo_root / "deck" / "build.mjs"
    node = args.node
    if not node.exists():
        raise SystemExit(f"Node runtime not found: {node}")
    result = subprocess.run([str(node), str(script)], cwd=repo_root, check=False)
    raise SystemExit(result.returncode)


def command_all(args: argparse.Namespace) -> None:
    train_args = argparse.Namespace(**vars(args))
    train_args.output = args.checkpoint
    command_train(train_args)
    demo_args = argparse.Namespace(
        checkpoint=args.checkpoint,
        output_dir=args.output_dir,
        device=args.device,
        samples=args.samples,
        seed=args.seed + 20,
    )
    command_demo(demo_args)
    score_args = argparse.Namespace(
        checkpoint=args.checkpoint,
        output=args.score_output,
        device=args.device,
        samples=args.score_samples,
        seed=args.seed + 40,
    )
    command_score(score_args)


def command_real_preprocess(args: argparse.Namespace) -> None:
    config = RealCtPreprocessConfig(
        target_shape=(args.size, args.size, args.size),
        hu_min=args.hu_min,
        hu_max=args.hu_max,
        seed=args.seed,
        val_fraction=args.val_fraction,
        test_fraction=args.test_fraction,
        task=args.task,
        positive_patches_per_case=args.positive_patches_per_case,
        negative_patches_per_case=args.negative_patches_per_case,
    )
    result = preprocess_msd_lung(args.raw_root, args.output, config=config)
    print(json.dumps(result, indent=2))


def command_real_summary(args: argparse.Namespace) -> None:
    print(json.dumps(load_cache_summary(args.data), indent=2))


def command_real_train(args: argparse.Namespace) -> None:
    config = RealCtTrainConfig(
        batch_size=args.batch_size,
        epochs=args.epochs,
        eval_every_steps=args.eval_every_steps,
        early_stop_acc=args.early_stop_acc,
        lr=args.lr,
        weight_decay=args.weight_decay,
        seed=args.seed,
    )
    result = train_real_ct_model(
        cache=args.data,
        output=args.output,
        config=config,
        device_name=args.device,
    )
    print(json.dumps(result, indent=2))


def command_real_demo(args: argparse.Namespace) -> None:
    device = resolve_device(args.device)
    model = load_real_ct_model(args.checkpoint, device)
    dataset = RealCtDataset(args.data, split=args.split, limit=args.samples, positive_only=True)
    score_dataset = RealCtDataset(args.data, split=args.split, limit=args.score_samples, positive_only=True)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    grid_path = args.output_dir / "real_ct_method_grid.png"
    case_path = args.output_dir / "real_ct_single_case.png"
    render_real_ct_grid(
        model=model,
        dataset=dataset,
        output=grid_path,
        device=device,
        sample_count=args.samples,
        methods=args.methods,
    )
    render_real_ct_single_case(
        model=model,
        dataset=dataset,
        output=case_path,
        device=device,
        sample_idx=0,
        methods=args.methods,
    )
    scores = score_real_ct_attributions(
        model=model,
        dataset=score_dataset,
        device=device,
        methods=args.methods,
    )
    save_scores(scores, args.score_output)
    print(
        json.dumps(
            {
                "grid": str(grid_path),
                "single_case": str(case_path),
                "scores": str(args.score_output),
                "summary": scores,
            },
            indent=2,
        )
    )


def command_web_export(args: argparse.Namespace) -> None:
    from .web_export import web_export as run_web_export

    generated_at = datetime.now(timezone.utc).isoformat()
    result = run_web_export(
        cache=args.data,
        checkpoint=args.checkpoint,
        out_dir=args.out,
        split=args.split,
        num_examples=args.samples,
        methods=args.methods,
        device_name=args.device,
        seed=args.seed,
        max_channels=args.max_channels,
        generated_at=generated_at,
        uv_lock=Path("uv.lock"),
    )
    print(json.dumps(result, indent=2))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="gradcam-repro",
        description="Reproduce the toy 3D Grad-CAM attribution experiment from GradCam.pptx.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    train_parser = subparsers.add_parser("train", help="Train the legacy synthetic CNN.")
    add_train_args(train_parser)
    train_parser.set_defaults(func=command_train)

    demo_parser = subparsers.add_parser("demo", help="Render attribution method comparison figures.")
    demo_parser.add_argument("--checkpoint", type=Path, default=DEFAULT_CHECKPOINT)
    demo_parser.add_argument("--output-dir", type=Path, default=DEFAULT_FIGURE_DIR)
    demo_parser.add_argument("--device", default="auto")
    demo_parser.add_argument("--samples", type=int, default=3)
    demo_parser.add_argument("--seed", type=int, default=27)
    demo_parser.set_defaults(func=command_demo)

    score_parser = subparsers.add_parser("score", help="Score attribution maps against the GT mask.")
    score_parser.add_argument("--checkpoint", type=Path, default=DEFAULT_CHECKPOINT)
    score_parser.add_argument("--output", type=Path, default=DEFAULT_SCORE_PATH)
    score_parser.add_argument("--device", default="auto")
    score_parser.add_argument("--samples", type=int, default=64)
    score_parser.add_argument("--seed", type=int, default=47)
    score_parser.set_defaults(func=command_score)

    deck_parser = subparsers.add_parser("deck", help="Build the editable PPTX deck.")
    deck_parser.add_argument("--node", type=Path, default=DEFAULT_NODE)
    deck_parser.set_defaults(func=command_deck)

    all_parser = subparsers.add_parser("all", help="Train then render all demo figures.")
    add_train_args(all_parser)
    all_parser.add_argument("--checkpoint", type=Path, default=DEFAULT_CHECKPOINT)
    all_parser.add_argument("--output-dir", type=Path, default=DEFAULT_FIGURE_DIR)
    all_parser.add_argument("--score-output", type=Path, default=DEFAULT_SCORE_PATH)
    all_parser.add_argument("--score-samples", type=int, default=64)
    all_parser.add_argument("--samples", type=int, default=3)
    all_parser.set_defaults(func=command_all)

    real_preprocess_parser = subparsers.add_parser(
        "real-preprocess",
        help="Preprocess MSD Task06_Lung CT volumes into a real-data classification cache.",
    )
    real_preprocess_parser.add_argument("--raw-root", type=Path, default=DEFAULT_REAL_CT_RAW_ROOT)
    real_preprocess_parser.add_argument("--output", type=Path, default=DEFAULT_REAL_CT_CACHE)
    real_preprocess_parser.add_argument("--size", type=int, default=48)
    real_preprocess_parser.add_argument("--hu-min", type=float, default=-1000.0)
    real_preprocess_parser.add_argument("--hu-max", type=float, default=400.0)
    real_preprocess_parser.add_argument("--seed", type=int, default=13)
    real_preprocess_parser.add_argument("--val-fraction", type=float, default=0.15)
    real_preprocess_parser.add_argument("--test-fraction", type=float, default=0.15)
    real_preprocess_parser.add_argument("--task", choices=["presence", "left_right"], default="presence")
    real_preprocess_parser.add_argument("--positive-patches-per-case", type=int, default=2)
    real_preprocess_parser.add_argument("--negative-patches-per-case", type=int, default=2)
    real_preprocess_parser.set_defaults(func=command_real_preprocess)

    real_summary_parser = subparsers.add_parser(
        "real-summary",
        help="Summarize a preprocessed real CT cache.",
    )
    real_summary_parser.add_argument("--data", type=Path, default=DEFAULT_REAL_CT_CACHE)
    real_summary_parser.set_defaults(func=command_real_summary)

    real_train_parser = subparsers.add_parser(
        "real-train",
        help="Train the real CT tumour-present patch classifier.",
    )
    real_train_parser.add_argument("--data", type=Path, default=DEFAULT_REAL_CT_CACHE)
    real_train_parser.add_argument("--output", type=Path, default=DEFAULT_REAL_CT_CHECKPOINT)
    real_train_parser.add_argument("--device", default="auto")
    real_train_parser.add_argument("--seed", type=int, default=13)
    real_train_parser.add_argument("--epochs", type=int, default=30)
    real_train_parser.add_argument("--eval-every-steps", type=int, default=8)
    real_train_parser.add_argument("--early-stop-acc", type=float, default=0.85)
    real_train_parser.add_argument("--batch-size", type=int, default=2)
    real_train_parser.add_argument("--lr", type=float, default=1e-3)
    real_train_parser.add_argument("--weight-decay", type=float, default=1e-4)
    real_train_parser.set_defaults(func=command_real_train)

    real_demo_parser = subparsers.add_parser(
        "real-demo",
        help="Render real CT Grad-CAM figures and mask-based attribution scores.",
    )
    real_demo_parser.add_argument("--data", type=Path, default=DEFAULT_REAL_CT_CACHE)
    real_demo_parser.add_argument("--checkpoint", type=Path, default=DEFAULT_REAL_CT_CHECKPOINT)
    real_demo_parser.add_argument("--output-dir", type=Path, default=DEFAULT_REAL_CT_FIGURE_DIR)
    real_demo_parser.add_argument("--score-output", type=Path, default=DEFAULT_REAL_CT_SCORE_PATH)
    real_demo_parser.add_argument("--device", default="auto")
    real_demo_parser.add_argument("--split", default="test")
    real_demo_parser.add_argument("--samples", type=int, default=3)
    real_demo_parser.add_argument("--score-samples", type=int, default=8)
    real_demo_parser.add_argument("--methods", nargs="+", default=REAL_CT_FAST_METHODS)
    real_demo_parser.set_defaults(func=command_real_demo)

    web_export_parser = subparsers.add_parser(
        "web-export",
        help="Export a static web data bundle (slices, attributions, activations, metrics).",
    )
    web_export_parser.add_argument("--data", type=Path, default=DEFAULT_REAL_CT_CACHE)
    web_export_parser.add_argument("--checkpoint", type=Path, default=DEFAULT_REAL_CT_CHECKPOINT)
    web_export_parser.add_argument("--out", type=Path, default=Path("web/public/data"))
    web_export_parser.add_argument("--split", default="test")
    web_export_parser.add_argument("--samples", type=int, default=3)
    web_export_parser.add_argument("--methods", nargs="+", default=None)
    web_export_parser.add_argument("--device", default="auto")
    web_export_parser.add_argument("--seed", type=int, default=13)
    web_export_parser.add_argument("--max-channels", type=int, default=6, help="Channels exported per layer (topk by mean); use a large value (e.g. 64) to export all.")
    web_export_parser.set_defaults(func=command_web_export)
    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    args.func(args)
